### ISSUE TITLE
CloudFormation fails consistently. It appears that when I try the QnA Bot option it fails consistently

### ISSUE THREAD

**Issue by pundaripothini** [aws-samples/amazon-transcribe-live-call-analytics#125]
I think it has to do with the Firehose data streams which isn't part of the architecture but the CFT seems to want to create them which is taking a very long time, Hence it fails. Here is an error from the rollback effort:

<html>
<body>

Cannot delete firehose: LCA-2024-QNABOT-VX01A57HKCP-FeedbackFirehose-IbX9VPykoWQO when encryption is in ENABLING status (Service: Firehose, Status Code: 400, Request ID: d1641e6f-8f08-1518-8f2d-1e29a270df77, Extended Request ID: OLnsdfj9H/uOEokjUCiBgrgw3JO3rXwfecwI+0309Sp3EBZMV4dd/s1o02zbz2KgJ0K74Q9QzftXuU/3PWhp9465BKQ0HOHX)
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by rstrahan** [comment]
@pundaripothini Can you comment if you still see this issue?
It is not reproducible for us. 
If it still happens for you using latest version (v0.8.13), can you let us know what parameters you use, what region you are deploying in, and any other details that might help us to reproduce and troubleshoot the issue.

**Comment by Moriuks** [comment]
Hello @rstrahan 

Just inserted the inputs mentioned in the blog (email, domain and cdir block). Beyond that, just the default parameters. 

Stack used info:
stack-id
arn:aws:cloudformation:us-west-2:xxxxxxxxx:stack/LCA/e5542da0-3536-11ef-8f6d-0a6c0bc37593

Description
Amazon Transcribe Live Call Analytics with Agent Assist - LCA (v0.8.13) (SO9072)

Region: did both (virginia/oregon) - same result 


Result

The root cause failure is likely related to a nested stack.

Logical ID
[QNABOTPLUGINBEDROCK](https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/events?stackId=arn%3Aaws%3Acloudformation%3Aus-west-2%3Axxxxxxxxx579%3Astack%2FLCA-QNABOTPLUGINBEDROCK-104JOQBVKEIE1%2Ffb0946d0-3536-11ef-a970-0600d75b50db)
NESTED
Status
CREATE_FAILED
Timestamp
2024-06-28 04:14:46 UTC-0600
Status reason
Embedded stack arn:aws:cloudformation:us-west-2:xxxxxxxxxxxx:stack/LCA-QNABOTPLUGINBEDROCK-104JOQBVKEIE1/fb0946d0-3536-11ef-a970-0600d75b50db was not successfully created: The following resource(s) failed to create: [TestBedrockModel].

**Comment by rstrahan** [comment]
Ah.. Most likely you have not enabled access to the require Bedrock Models.  Please confirm this by navigating into the nested stack (you can do this from the Resources tab of the main stack) nd look for the first CREATE_FAILED message - it will have the details reported against the TestBedrockModel resource.  

To fix it, please follow the model access step outlined in the blog post - below..
![image](https://github.com/aws-samples/amazon-transcribe-live-call-analytics/assets/10953374/7d0dc14f-271e-4229-bea0-85d9adb37543)

Let us know if that works.

**Comment by rstrahan** [comment]
@Moriuks Assuming you were able to resolve issue based on my response above?  If so, would be great to confirm.

Meanwhile - I will add a task to check for required Bedrock model enablement in the main stack, so if it fails again it will be easier to troubleshoot.

**Comment by rstrahan** [comment]
> I will add a task to check for required Bedrock model enablement in the main stack, so if it fails again it will be easier to troubleshoot.

This check will be in the next release. currently in the develop branch.

Closing issue since no response to last message.
