### ISSUE TITLE
Urgent issue- CodeBuildRun: CREATE_FAILED

### ISSUE THREAD

**Issue by Geoffmoss77** [aws-samples/amazon-transcribe-live-call-analytics#178]
Hi LCA Team,

When deploying to the EU-WEST-2 I get the following error

The file in the Docker file can not locate:
client-transcribe-streaming

LCA-v1-GENESYSAUDIOHOOKTRANSCRIBERSTACK-84I7K34IVD3G_CodeBuildRun_SU0ZTOKF
Custom::CodeBuildRun
CREATE_FAILED

Please can you fix?

**Comment by rstrahan** [comment]
Hi Geoffrey - can you please post
1. exact steps to reproduce the problem (stack params used, etc )
2. Details of where/when you see the error(s) with screenshots
3. Details of any troubleshooting you have already done, results, and where exactly you are stuck in your troubleshooting.

Thanks
Bob



Sent from Workspace ONE Boxer

On Aug 13, 2024 4:20 AM, Geoffrey Rowland ***@***.***> wrote:

Hi LCA Team,

When deploying to the EU-WEST-2 I get the following error

The file in the Docker file can not locate:
client-transcribe-streaming

LCA-v1-GENESYSAUDIOHOOKTRANSCRIBERSTACK-84I7K34IVD3G_CodeBuildRun_SU0ZTOKF
Custom::CodeBuildRun
CREATE_FAILED

Please can you fix?

**Comment by rstrahan** [comment]
Can you clarify if it fails when you 
(1) run the publish script (which creates the CF templates from the repo), or 
(2) when you deploy the stack using the created templates.
Please attach screenshots of the error that you are reporting, and the list of clear steps to reproduce it. 
Thanks

**Comment by rstrahan** [comment]
Looking at that COPY command now.. I do see the problem - it looks like all releases prior to 0.9.0 included the `client-transcribe-streaming` directory, but this directory was removed in 0.9.0 - presumably because it is no longer needed (I think it was initially introduced when we added Transcribe Call Analytics api support to LCA before the SDK was published.. but that reason no longer exists)
 
However, it appears that the COPY command in the Dockerfile was not removed.. 

I think the right fix is the one you made already - i.e. to simply remove the COPY command.  

Can you verify if your deployment of v0.9.1 works as expected now that you have removed that line and published your own templates?  

If you verify it works, I can prioritize making a new release (v0.9.2) with that fix included.

Thanks!!

**Comment by Geoffmoss77** [comment]
Hi Bob we were able to deploy with the COPY line removed both Call Audio Processor set as Chime and Call Transcriber Lambda functions selected.

**Comment by rstrahan** [comment]
Great! And the processing/transcribing all works as expected after this change?

I will try to get a new release soon with the fix.

Thanks for reporting it!


Sent from Workspace ONE Boxer

On Aug 13, 2024 11:36 AM, Geoffrey Rowland ***@***.***> wrote:

Hi Bob we were able to deploy with the COPY line removed both Call Audio Processor set as Chime and Call Transcriber Lambda functions selected.

**Comment by Geoffmoss77** [comment]
Hi Bob everything seems to work except the Voice Tone Analysis does not seem to have any data. We have been testing multiple calls.

Do I have to enable something else for it to function on top of using Chime?

**Comment by Geoffmoss77** [comment]
![2024-08-14 09_16_11-Live Call Analytics with Agent Assist and 30 more pages - Work - Microsoft​ Edge](https://github.com/user-attachments/assets/1512f717-37b4-4c50-bec0-c091e89e29e8)
Please see attached.

**Comment by rstrahan** [comment]
Hi @Geoffmoss77 - Hopefully latest build - v0.9.2 - works for you..  Thanks so much for finding and reporting the issue.

Regarding Voice Tone - unfortunately that feature depends on the Call Audio Source involving Chime SDK Voice Connector (SIPREC) - or the demo Asterisk setup which also uses Chime SDK Voice Connector, but it doesn't work with the Genesys AudioHook webseocket server..  Sorry.

![image](https://github.com/user-attachments/assets/f981f3df-dbfe-4856-b6a6-6e25ab2bb005)
